version: '3'
services:
    laravel:
        image: ambientum/php:7.4-nginx
        ports:
            - '8080:8080'
        volumes:
            - '.:/var/www/app'
        networks:
            - laravel
        depends_on:
            - pgsql
    pgsql:
        image: 'postgres'
        ports:
            - '5432:5432'
        environment:
            PGPASSWORD: 'secret'
            POSTGRES_DB: 'boilerplate'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'secret'
        volumes:
            - 'pgsql:/var/lib/postgresql/data'
        networks:
            - laravel
        healthcheck:
          test: ["CMD", "pg_isready", "-q", "-d", "boilerplate", "-U", "postgres"]
          retries: 3
          timeout: 5s
networks:
    laravel:
      driver: bridge
volumes:
    pgsql:
      driver: local
